const canvas=document.querySelector('#gameCanvas'),ctx=canvas.getContext('2d');
const mini=document.querySelector('#miniMap'),mctx=mini.getContext('2d');
const ui={overlay:document.querySelector('#gameOverlay'),start:document.querySelector('#startButton'),score:document.querySelector('#scoreValue'),length:document.querySelector('#lengthValue'),kills:document.querySelector('#killsValue'),best:document.querySelector('#bestValue'),rank:document.querySelector('#rankList'),progress:document.querySelector('#challengeProgress'),challenge:document.querySelector('#challengeText'),status:document.querySelector('#statusText'),sound:document.querySelector('#soundButton'),wheel:document.querySelector('#directionWheel'),knob:document.querySelector('.wheel-knob'),boost:document.querySelector('#boostButton'),difficultyBadge:document.querySelector('#difficultyBadge')};
const W=canvas.width,H=canvas.height,cell=16,arena={w:60,h:40};
let soundOn=true,running=false,paused=false,last=0,accumulator=0,step=64,score=0,kills=0,best=Number(localStorage.snakeArenaBest||0);
let snake,bots,foods,remains,powerUps,sparks,direction,nextDirection,wheelActive=false,boosting=false,difficulty='easy',botSpawnTimer=0,nextBotSpawn=2500,powerUpTimer=0,magnetTimer=0,playerShield=0;
const colors=['#ffbb4e','#f474cc','#9a7bff','#4bc7ff','#ff785c']; const difficultyConfig={easy:{label:'新手',step:74,bots:3,boost:.76},normal:{label:'标准',step:64,bots:5,boost:.9},hard:{label:'极限',step:48,bots:8,boost:1.06}};
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function reset(){const config=difficultyConfig[difficulty];step=config.step;snake=Array.from({length:22},(_,i)=>({x:29-i*.36,y:20}));direction=nextDirection={x:1,y:0};score=0;kills=0;sparks=[];remains=[];powerUps=[];powerUpTimer=0;magnetTimer=0;playerShield=0;foods=Array.from({length:35},food);bots=[];for(let i=0;i<config.bots;i++)spawnBot();updateUI();setKnob(direction)}
function food(){const star=Math.random()<.16;return{x:2+Math.random()*56,y:2+Math.random()*36,hue:star?45:Math.random()*80+140,pulse:Math.random()*6,star}}
function makeBot(name,color,x,y,dx,dy){const body=[];for(let i=0;i<5+Math.floor(Math.random()*8);i++)body.push({x:x-i*dx,y:y-i*dy});return{name,color,body,dir:{x:dx,y:dy},turn:35+Math.random()*55,score:body.length*14,shield:5000}} function spawnPowerUp(){const type=Math.random()<.5?'magnet':'shield',angle=Math.random()*Math.PI*2,speed=.025+Math.random()*.03;powerUps.push({type,x:4+Math.random()*52,y:4+Math.random()*32,dx:Math.cos(angle)*speed,dy:Math.sin(angle)*speed,life:7000+Math.random()*6000,pulse:Math.random()*6})} function spawnBot(){const edge=Math.floor(Math.random()*4),margin=3;let x=edge<2?(edge?arena.w-margin:margin):margin+Math.random()*(arena.w-margin*2),y=edge>1?(edge===2?margin:arena.h-margin):margin+Math.random()*(arena.h-margin*2);const dirs=[{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}],dir=dirs[Math.floor(Math.random()*dirs.length)],name=['RIFT','NOVA','PIXEL','ECHO','GHOST'][Math.floor(Math.random()*5)];bots.push(makeBot(name,colors[Math.floor(Math.random()*colors.length)],x,y,dir.x,dir.y));burst(x,y,'#7defff')}
function start(){reset();botSpawnTimer=0;nextBotSpawn=1800+Math.random()*3200;running=true;paused=false;ui.overlay.classList.add('hidden');ui.status.textContent='正在战斗';last=performance.now();requestAnimationFrame(loop);beep(450,.08)}
function loop(now){if(!running)return;const delta=Math.min(now-last,100);last=now;if(!paused){botSpawnTimer+=delta;powerUpTimer+=delta;magnetTimer=Math.max(0,magnetTimer-delta);playerShield=Math.max(0,playerShield-delta);bots.forEach(bot=>bot.shield=Math.max(0,bot.shield-delta));powerUps=powerUps.filter(item=>{item.life-=delta;item.x+=item.dx*delta;item.y+=item.dy*delta;if(item.x<2||item.x>58)item.dx*=-1;if(item.y<2||item.y>38)item.dy*=-1;return item.life>0});if(botSpawnTimer>nextBotSpawn){spawnBot();botSpawnTimer=0;nextBotSpawn=1800+Math.random()*3200}if(powerUpTimer>5000+Math.random()*4000&&powerUps.length<2){spawnPowerUp();powerUpTimer=0}accumulator+=delta;while(accumulator>step){tick();accumulator-=step}}draw(now);requestAnimationFrame(loop)}
function tick(){direction=nextDirection;const speed=boosting?difficultyConfig[difficulty].boost:.48;const head={x:snake[0].x+direction.x*speed,y:snake[0].y+direction.y*speed};const collision=head.x<.45||head.y<.45||head.x>arena.w-.45||head.y>arena.h-.45||snake.slice(8).some(p=>dist(head,p)<.52)||bots.some(bot=>bot.body.some(p=>dist(head,p)<.66));if(collision&&!playerShield){gameOver();return}powerUps=powerUps.filter(item=>{if(dist(head,item)<.9){if(item.type==='magnet')magnetTimer=7000;else playerShield=7000;burst(item.x,item.y,item.type==='magnet'?'#ff687b':'#79f3ff');beep(item.type==='magnet'?520:760,.1);return false}return true});snake.unshift(head);let growth=0;if(magnetTimer)foods.forEach(f=>{const dx=head.x-f.x,dy=head.y-f.y,d=Math.hypot(dx,dy);if(d<7&&d>.1){f.x+=dx/d*.22;f.y+=dy/d*.22}});foods.forEach((f,i)=>{if(dist(head,f)<.75){foods.splice(i,1);foods.push(food());const reward=f.star?{score:35,growth:12,color:'#ffe06b',tone:880}:{score:10,growth:3,color:'#bfff57',tone:660};score+=reward.score;growth+=reward.growth;burst(f.x,f.y,reward.color);beep(reward.tone,.06)}});remains=remains.filter(part=>{if(dist(head,part)<.72){score+=4;growth+=1;burst(part.x,part.y,part.color);return false}return true});const targetLength=22+score/10*3+growth;while(snake.length>targetLength)snake.pop();bots.forEach(moveBot);sparks=sparks.filter(s=>--s.life>0);updateUI()}
function moveBot(bot){bot.turn--;const h=bot.body[0];if(bot.turn<0){const dirs=[{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}].filter(d=>d.x!==-bot.dir.x||d.y!==-bot.dir.y);bot.dir=dirs[Math.floor(Math.random()*dirs.length)];bot.turn=20+Math.random()*70}const n={x:h.x+bot.dir.x,y:h.y+bot.dir.y};const hitsBoundary=n.x<.5||n.x>arena.w-.5||n.y<.5||n.y>arena.h-.5;const hitsPlayer=snake.some(part=>dist(n,part)<.6);const hitsOtherSnake=bots.some(other=>other!==bot&&other.body.some(part=>dist(n,part)<.55));if(hitsBoundary||hitsPlayer||hitsOtherSnake){if(bot.shield){const dirs=[{x:1,y:0},{x:-1,y:0},{x:0,y:1},{x:0,y:-1}].filter(d=>d.x!==-bot.dir.x||d.y!==-bot.dir.y);bot.dir=dirs[Math.floor(Math.random()*dirs.length)];bot.turn=20+Math.random()*40;return}remains.push(...bot.body.map(part=>({...part,color:bot.color})));bots.splice(bots.indexOf(bot),1);burst(h.x,h.y,bot.color);if(hitsPlayer)kills++;return}bot.body.unshift(n);bot.body.pop()}
function burst(x,y,color){for(let i=0;i<12;i++)sparks.push({x:x+.5,y:y+.5,dx:(Math.random()-.5)*.18,dy:(Math.random()-.5)*.18,life:12+Math.random()*12,color})}
function gameOver(){running=false;best=Math.max(best,score);localStorage.snakeArenaBest=best;ui.status.textContent='本局结束';ui.overlay.classList.remove('hidden');ui.overlay.querySelector('h1').textContent='战斗结束';ui.overlay.querySelector('p').textContent=`获得 ${score} 分 · 蛇身长度 ${Math.floor(snake.length/3)}`;ui.start.innerHTML='再次开战 <span>→</span>';beep(105,.28)}
function updateUI(){const length=Math.floor(snake.length/3);ui.score.textContent=String(score).padStart(4,'0');ui.length.textContent=length;ui.kills.textContent=kills;ui.best.textContent=best;const p=Math.min(length/30*100,100);ui.progress.style.width=p+'%';ui.challenge.textContent=`${length} / 30`;const entries=[...bots.map(b=>({name:b.name,color:b.color,score:b.score})),{name:'你',color:'#32e6d0',score:score+length*10,mine:true}].sort((a,b)=>b.score-a.score);ui.rank.innerHTML=entries.slice(0,6).map((r,i)=>`<div class="rank-item ${r.mine?'mine':''}"><span class="rank-num">${i+1}</span><i class="rank-dot" style="background:${r.color}"></i><span class="rank-name">${r.name}</span><span class="rank-score">${r.score}</span></div>`).join('')}
function draw(time){ctx.clearRect(0,0,W,H);ctx.fillStyle='#06111e';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(89,171,202,.11)';for(let x=0;x<=W;x+=cell){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<=H;y+=cell){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const glow=ctx.createRadialGradient(W/2,H/2,20,W/2,H/2,500);glow.addColorStop(0,'rgba(21,89,112,.16)');glow.addColorStop(1,'rgba(2,8,15,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);foods.forEach(f=>drawFood(f,time));powerUps.forEach(item=>drawPowerUp(item,time));remains.forEach(drawRemains);bots.forEach(drawBot);drawSnake();sparks.forEach(s=>{ctx.globalAlpha=s.life/24;ctx.fillStyle=s.color;ctx.fillRect((s.x+s.dx*(24-s.life))*cell-2,(s.y+s.dy*(24-s.life))*cell-2,4,4);ctx.globalAlpha=1});drawRadar();if(paused){ctx.fillStyle='rgba(0,8,18,.58)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#eaf4ff';ctx.font='700 38px Barlow Condensed';ctx.textAlign='center';ctx.fillText('已暂停',W/2,H/2)}}
function drawFood(f,time){const x=f.x*cell,y=f.y*cell,r=4+Math.sin(time/220+f.pulse)*1.5;ctx.save();ctx.shadowBlur=f.star?22:15;ctx.shadowColor=f.star?'#ffe06b':`hsl(${f.hue},100%,65%)`;ctx.fillStyle=f.star?'#ffe06b':`hsl(${f.hue},100%,68%)`;if(f.star){ctx.beginPath();for(let i=0;i<10;i++){const angle=-Math.PI/2+i*Math.PI/5,rad=i%2?3:r+2;const px=x+Math.cos(angle)*rad,py=y+Math.sin(angle)*rad;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}else{ctx.beginPath();ctx.arc(x,y,r,0,7)}ctx.fill();ctx.restore()}
function drawPowerUp(item,time){const x=item.x*cell,y=item.y*cell,bob=Math.sin(time/180+item.pulse)*2;ctx.save();ctx.translate(x,y+bob);ctx.shadowBlur=20;ctx.shadowColor=item.type==='magnet'?'#ff687b':'#79f3ff';ctx.fillStyle=item.type==='magnet'?'#ff687b':'#79f3ff';ctx.beginPath();ctx.arc(0,0,8,0,7);ctx.fill();ctx.fillStyle='#07111e';ctx.font='bold 12px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(item.type==='magnet'?'U':'⛨',0,1);ctx.restore()} function drawRemains(part){ctx.save();ctx.globalAlpha=.72;ctx.shadowBlur=10;ctx.shadowColor=part.color;ctx.fillStyle=part.color;ctx.beginPath();ctx.arc(part.x*cell,part.y*cell,4.5,0,7);ctx.fill();ctx.restore()} function drawBot(bot){const shielded=bot.shield>0;bot.body.slice().reverse().forEach((p,i)=>{ctx.save();if(shielded){ctx.shadowBlur=13;ctx.shadowColor='#74edff'}ctx.fillStyle=bot.color;ctx.globalAlpha=.36+i/bot.body.length*.56;ctx.beginPath();ctx.roundRect(p.x*cell+2,p.y*cell+2,cell-4,cell-4,5);ctx.fill();ctx.restore()});if(shielded){const h=bot.body[0];ctx.save();ctx.strokeStyle='rgba(123,239,255,.85)';ctx.lineWidth=1.5;ctx.setLineDash([3,2]);ctx.beginPath();ctx.arc(h.x*cell,h.y*cell,12+Math.sin(bot.shield/170)*2,0,7);ctx.stroke();ctx.restore()}ctx.globalAlpha=1}
function drawSnake(){if(playerShield){const h=snake[0];ctx.save();ctx.strokeStyle='rgba(121,243,255,.88)';ctx.lineWidth=2;ctx.shadowBlur=16;ctx.shadowColor='#79f3ff';ctx.beginPath();ctx.arc(h.x*cell,h.y*cell,15+Math.sin(playerShield/140)*2,0,7);ctx.stroke();ctx.restore()}snake.slice().reverse().forEach((p,i)=>{const r=i===snake.length-1?7:5.8;ctx.save();ctx.shadowBlur=i===snake.length-1?20:7;ctx.shadowColor='#2de4d0';ctx.fillStyle=i===snake.length-1?'#b8ff56':'#24cbbf';ctx.beginPath();ctx.arc(p.x*cell,p.y*cell,r,0,7);ctx.fill();ctx.restore()});const h=snake[0];ctx.fillStyle='#05202a';ctx.beginPath();ctx.arc((h.x+direction.y*.17+direction.x*.2)*cell,(h.y-direction.x*.17+direction.y*.2)*cell,1.8,0,7);ctx.arc((h.x-direction.y*.17+direction.x*.2)*cell,(h.y+direction.x*.17+direction.y*.2)*cell,1.8,0,7);ctx.fill()}
function drawRadar(){mctx.fillStyle='#06121e';mctx.fillRect(0,0,132,88);mctx.strokeStyle='rgba(84,207,205,.17)';mctx.strokeRect(1,1,130,86);foods.forEach(f=>{mctx.fillStyle='#bfff57';mctx.fillRect(f.x/60*132,f.y/40*88,2,2)});bots.forEach(b=>{mctx.fillStyle=b.color;mctx.fillRect(b.body[0].x/60*132,b.body[0].y/40*88,4,4)});mctx.fillStyle='#32e6d0';mctx.fillRect(snake[0].x/60*132-2,snake[0].y/40*88-2,5,5)}
function beep(freq,duration){if(!soundOn||!window.AudioContext)return;const ac=new AudioContext(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+duration)}
function setDir(dir){const size=Math.hypot(dir.x,dir.y);if(!size)return;const normalized={x:dir.x/size,y:dir.y/size};if(normalized.x!==-direction.x||normalized.y!==-direction.y){nextDirection=normalized;setKnob(normalized)}}
function setKnob(dir){if(!ui.knob)return;ui.knob.style.transform=`translate(${dir.x*26}px, ${dir.y*26}px)`}
function togglePause(){if(running){paused=!paused;ui.status.textContent=paused?'已暂停':'正在战斗'}}
function setBoost(active){boosting=active;if(ui.boost)ui.boost.classList.toggle('active',active)} window.addEventListener('keydown',e=>{const map={ArrowUp:{x:0,y:-1},w:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1},ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0}};if(map[e.key]){e.preventDefault();setDir(map[e.key])}if(e.code==='Shift'){e.preventDefault();setBoost(true)}if(e.code==='Space'){e.preventDefault();togglePause()}});window.addEventListener('keyup',e=>{if(e.code==='Shift')setBoost(false)});
function setWheelDirection(event){const rect=ui.wheel.getBoundingClientRect(),x=event.clientX-rect.left-rect.width/2,y=event.clientY-rect.top-rect.height/2;setDir({x,y})}ui.wheel.addEventListener('pointerdown',e=>{if(e.target.closest('.wheel-center')){togglePause();return}wheelActive=true;ui.wheel.setPointerCapture(e.pointerId);setWheelDirection(e)});ui.wheel.addEventListener('pointermove',e=>{if(wheelActive)setWheelDirection(e)});ui.wheel.addEventListener('pointerup',()=>wheelActive=false);document.querySelectorAll('.difficulty').forEach(button=>button.addEventListener('click',()=>{if(running)return;difficulty=button.dataset.difficulty;document.querySelectorAll('.difficulty').forEach(item=>item.classList.toggle('active',item===button));ui.difficultyBadge.textContent=difficultyConfig[difficulty].label}));['pointerdown','touchstart'].forEach(event=>ui.boost.addEventListener(event,()=>setBoost(true)));['pointerup','pointerleave','pointercancel','touchend'].forEach(event=>ui.boost.addEventListener(event,()=>setBoost(false)));ui.start.addEventListener('click',start);ui.sound.addEventListener('click',()=>{soundOn=!soundOn;ui.sound.style.opacity=soundOn?1:.38});reset();draw(0);
